# Generated by Django 4.0.4 on 2022-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papi', '0005_auto_20220411_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='good place', max_length=10000),
        ),
    ]
