# Generated by Django 4.0.4 on 2022-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papi', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='GBLink',
            field=models.URLField(default='https://ihglb.business.site/', max_length=2000),
        ),
    ]
