# Generated by Django 4.0.4 on 2022-04-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papi', '0007_product_gblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GBLink',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
