# Generated by Django 4.0.4 on 2022-05-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papi', '0008_alter_product_gblink_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VORCANOES', 'vorcanoes'), ('TRANSPORTANTION', 'transportation'), ('ACCOMODATION', 'accomodation'), ('HOTEL/RESTAURANTS', 'hotel/restaurants'), ('NATIONAL PARKS', 'national Parks'), ('CULTURE & HERITAGE', 'culture & heritage'), ('SPORTS & ADVANTURE', 'sports & advanture'), ('HILLS', 'hills')], default='VORCANOES', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('congo', 'CONGO'), ('kenya', 'KENYA'), ('burundi', 'BURUNDI'), ('south sudan', 'SOUTH SUDAN'), ('uganda', 'UGANDA'), ('tanzania', 'TANZANIA'), ('rwanda', 'RWANDA')], default='congo', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.CharField(choices=[('free', 'FREE'), ('not free', 'NOT FREE')], default='free', max_length=25),
        ),
    ]
