# Generated by Django 4.0.4 on 2022-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papi', '0009_alter_product_category_alter_product_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VORCANOES', 'vorcanoes'), ('TRANSPORTANTION', 'transportation'), ('ACCOMODATION', 'accomodation'), ('RESTAURANTS', 'restaurants'), ('NATIONAL PARKS', 'national Parks'), ('CULTURE & HERITAGE', 'culture & heritage'), ('SPORTS & ADVANTURE', 'sports & advanture'), ('HILLS', 'hills')], default='VORCANOES', max_length=25),
        ),
    ]
